version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      uncategorized:
        applies-to: version-updates
        patterns:
          - "*"
      laverve:
        applies-to: version-updates
        patterns:
          - "@laverve*"
      react:
        applies-to: version-updates
        patterns:
          - "react*"
          - "*react"
          - "*react*"
    ignore:
      - dependency-name: "@storybook/*"
      - dependency-name: "storybook"