name: Release Train

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/lint
            - uses: ./.github/actions/build
            - uses: ./.github/actions/test

    Release-Please:
        runs-on: ubuntu-latest

        needs: [test]

        concurrency: Draft-Release

        outputs:
            timer_release_created: ${{ steps.release.outputs['packages/timer--release_created'] }}
            use_parent_size_release_created: ${{ steps.release.outputs['packages/use-parent-size--release_created'] }}

        steps:
            - uses: actions/checkout@v4
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    Publish-NPM-Packages:
        needs: [Release-Please]

        runs-on: ubuntu-latest

        concurrency: Publish-NPM-Packages

        if: ${{ needs.Release-Please.outputs.timer_release_created || needs.Release-Please.outputs.use_parent_size_release_created }}

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/build
            - uses: ./.github/actions/publish
              if: ${{ needs.Release-Please.outputs.timer_release_created }}
              with:
                  package: packages/timer
            - uses: ./.github/actions/publish
              if: ${{ needs.Release-Please.outputs.use_parent_size_release_created }}
              with:
                  package: packages/use-parent-size

