name: Release Train

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/lint

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/build
            - uses: ./.github/actions/test

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: "main"
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/build-storybook

    Release-Please:
        runs-on: ubuntu-latest

        needs: [test, lint, build]

        concurrency: Draft-Release

        outputs:
            timer_release_created: ${{ steps.release.outputs['packages/components/timer--release_created'] }}

        steps:
            - uses: actions/checkout@v4
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    Publish-NPM-Packages:
        needs: [Release-Please]

        runs-on: ubuntu-latest

        concurrency: Publish-NPM-Packages

        if: ${{ needs.Release-Please.outputs.wordsearch_release_created || needs.Release-Please.outputs.maze_release_created }}

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: "npm"
            - uses: ./.github/actions/install
            - uses: ./.github/actions/build
            - uses: ./.github/actions/publish
              if: ${{ needs.Release-Please.outputs.timer_release_created }}
              with:
                  package: packages/components/timer

    Publish-GH-Pages:
        needs: [Release-Please]

        if: ${{ needs.Release-Please.outputs.timer_release_created }}

        runs-on: ubuntu-latest

        concurrency: Publish-GH-Pages

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy artifact to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: "github-pages"
